### ISSUE TITLE
Kotak - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/Pre-production#101]
1. /select - you can't create your own attributes e.g. fulfillments.end.location.address.same_as_delivery;
2. /init, /confirm - billing.address.country is blank;
3. /confirm - fulfillments.end.location.name / country is blank;
4. No /update, /track, /support

**Comment by BLR-0118** [comment]
@taukilali - pls fix the above. For /update, pls comply with the latest version of contract

**Comment by BLR-0118** [comment]
Issues from logs submitted by Uengage while testing with Kotak buyer app:
1. all your timestamps are having invalid format (Context, other attrs like created_at, updated_at). It should be RFC3339 compliant with exactly 3 digits in ms followed by Z and time in UTC;
2. ttl should be 30s ("PT30S") in all API context;
3. /select, /init, /confirm API call is showing the uengage endpoint for /on_search. It should just show their uri;
4. fulfillment_id which comes in /on_select should be preserved in all forward APIs like /init, /confirm;
5. payment block in /init should actually come in /confirm as pre-paid payment collection by buyer app happens before /confirm;
6. /confirm - why is payment showing Rs 1 here while in /init it was showing the actual amount 101.05?
7.

**Comment by BLR-0118** [comment]
@taukilali

**Comment by BLR-0118** [comment]
It's really hard to review your logs as it includes all internal API logs as well. I'm only interested in the logs for APIs called using the ONDC protocol and not any of the internal APIs. Pls resubmit the logs just like the other participants. You can see from the GitHub repo how they're submitting logs.

**Comment by BLR-0118** [comment]
@taukilali

**Comment by BLR-0118** [comment]
1. /init - payment object shouldn't be there (check the [contract](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit)). Payment with type "ON-ORDER" and status "PAID" comes in /confirm for pre-paid payments;
2. /init, /confirm - there should be a link between the item id & fulfillment_id which would be the same as what comes in /on_select;
3. /cancel - reason id shows "3" when it should be "003" as per the [doc](https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit)
4. No /status, /track, /update APIs?

**Comment by BLR-0118** [comment]
@samakshrawat16 @taukilali

**Comment by BLR-0118** [comment]
1. /confirm - shows state as "Bangalore"?
2. No APIs for /update, /status, /track?

**Comment by BLR-0118** [comment]
@samakshrawat16

**Comment by BLR-0118** [comment]
Logs with Bizom:
1. /on_select - fulfillment state is "non-serviceable". How the buyer app is handling it isn't clear.
2. /init - fulfillment id is null in the fulfillments array. It should be returning the same id coming in /on_select;
3. /confirm - fulfillment id is null in the fulfillments array. It should be returning the same id coming in /on_init;
4. /confirm - payment.params.amount shows 4 decimal places when everything else is 2 decimal places. Why?
5. /confirm - payment.params should have transaction_id for payment successfully collected;
6. /update - not sure what is being returned (as quantity shows 0 for items 119 & 114 when you're actually expected to show quantity being returned) and how the refund amount is calculated;

**Comment by BLR-0118** [comment]
@samakshrawat16

**Comment by BLR-0118** [comment]
1. Some of the API responses aren't in the logs, so not clear whether the following is being followed:
a. transaction_id and message_id should be different in every API request (this is not always the case);
b. same message_id should be in a request/response pair; if you get a different message id in response, you should reject it;
c. same transaction_id from select onwards (for all APIs) - this seems to be followed;
2. Why are so many different values (estimated_value, computed_value, etc. etc.) being shown in /confirm? This should be exactly the same as what's in /on_select & /on_init
3. Also, pls share the updated APK with fixes for the issues shared with Amit on Friday. Pls fix this ASAP so we can clear your app by tomorrow & you can get into the new prod env
@samakshrawat16

**Comment by BLR-0118** [comment]
Pls see 1a above. I see the transaction_id and message_id being the same in /search.

**Comment by BLR-0118** [comment]
@samakshrawat16 request Kotak team to pls check each of the issues mentioned yesterday & fix them before submitting their logs.

**Comment by taukilali** [comment]
@BLR-0118 Sure and i will make sure to be fixed today

**Comment by BLR-0118** [comment]
Logs with Gofrugal seller app:
1. /on_search - returns empty catalog. How did you then select an item from the empty catalog in /select and execute the other APIs?

**Comment by BLR-0118** [comment]
@samakshrawat16

**Comment by BLR-0118** [comment]
1. /on_search - the json returned here seems to be invalid when I tried to enter into jsonformatter.org (seems like cut & paste error or did the adapter truncate the logs). How were you able to display it?
2. /on_select - should have a fulfillment_id;
3. /init - fulfillment_id should be assigned by the seller app;
4. /confirm - payment.params is invalid.
5. /on_init doesn't have quote.price.offered_value but /confirm has value="508" and offered_value="0". Trying to understand what it means since this value is supposed to be filled up by the seller app alone;
6. /update - order.state is empty (should have the latest val)
7. /on_update - doesn't have item level status. When an item is being returned through /update, if the return is approved or picked, refund can be initiated. not sure how you calculated the refund amount without finding the difference between the latest order value (with buyer app) and as per the quote sent by the seller app.

**Comment by BLR-0118** [comment]
@samakshrawat16

**Comment by BLR-0118** [comment]
logs verified
