### ISSUE TITLE
NowFloats - Compliance Check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/Pre-production#166]
Can you pls submit both request & response logs? Will make it easier to verify.

**Comment by BLR-0118** [comment]
@varun-nf

**Comment by varun-nf** [comment]
@BLR-0118 Updated logs

**Comment by BLR-0118** [comment]
1. /search request GPS coords indicate a location in Bengaluru whereas the response came from a provider whose GPS coords indicate a location in Secunderabad with serviceability radius of 5km. How's this possible?
2. /on_search catalog item of Kurkure is actually packaged foods. Will you be providing back image (for compliance reqs);
3. /on_select - needs to comply with the API contract [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit)
4. /on_select fulfillments rating was 0. How did it become 5 in /on_init? Note that we don't support rating yet. Also, some of the keys in /on_init such as fulfillment TAT, etc. are not part of the contract;
5. /on_init - quote breakup keys used not compliant with API contract;
6. /on_confirm - order state should be "Accepted" per the new order & fulfillment states;
7. /on_status - pls update the order & fulfillment state as per the new order & fulfillment states;
8. /on_update - same as 7;
9. No /status, /update APIs?

**Comment by BLR-0118** [comment]
@varun-nf

**Comment by varun-nf** [comment]
https://github.com/ONDC-Official/Pre-production/pull/182
This PR have new logs.
Replies to Log remarks
1. We disabled serviceability check since some of buyer apps still using std:080 for Hyd eg:MyStore. Later we wont send on_search if location is not serviceable by the sellers.

9. Update type billing(For settlement) supported, unable to test End to end. I had tested directly with postman by commenting authentication. 
Status API is not being called by plotch buyer app. So unable to submit log for status request.
We made direct calls of on_status and on_update for every order/fulfillment status change.

**Comment by BLR-0118** [comment]
1. /on_search & other APIs - timestamp is not in valid format;
2. /on_init - why does it say payment.collected_by="BAP" (this will happen in /confirm, you don't need to propose payment collection by the counterparty here);
3. Can you pls DM me on what issues you're having with Plotch on /update, /status?

**Comment by varun-nf** [comment]
$2 We want payment to be collected by BAP. We don't support COD. So I am passing payment.collected_by="BAP" in on_init.
Is there any way to achieve this?

**Comment by BLR-0118** [comment]
1. /on_status - fulfillment state of "Serviceable" is not a valid post order state. Pls check the API contract [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit) in /on_status for details;
2. /on_status - isn't complete; doesn't have the payment collected by and similar details. Pls note that /on_status is expected to have the complete order items trail (including part return, cancel), updated order & fulfillment state and current order value;
@varun-nf

**Comment by varun-nf** [comment]
New Logs
https://github.com/ONDC-Official/Pre-production/pull/201

Note:
We tested update api for settlement our self through postman.

@BLR-0118

**Comment by BLR-0118** [comment]
1. /init - items.fulfillment_id missing, fulfillments array is empty (it's supposed to have the end address);
2. /on_init - payment type "ON-ORDER" without collected_by doesn't make sense. If collected_by = "BAP", you should only be sending the settlement details here;
3. /confirm - fulfillment_id empty, items.fulfillment_id missing.
4. /on_confirm, /on_status, /on_update - items.fulfillment_id is not the same as fulfillment_id. Why?
5. /select has transaction_id in one format but /init onwards uses UUID. Why?
6. whar does self-prepared json for /update mean?

**Comment by BLR-0118** [comment]
@varun-nf @samakshrawat16

**Comment by varun-nf** [comment]
@BLR-0118 
Updated logs https://github.com/ONDC-Official/Pre-production/pull/232
2. We not sending payment type now as collected by will be BAP for this MVP.
4. This fulfillment id issue fixed. as we do self delivery we using transactionId itself as fulfillmentId.
6. We are unable to test update api for settlement with buyer apps, so we created json ourself and caller our server by commenting authentication.

**Comment by BLR-0118** [comment]
1. /on_confirm - shouldn't order.state be "Accepted" since it seems your order is auto-accepted and in /on_status, the order state shows as "In-progress"? Pls make this change.
Clearing your transaction logs. No need to resubmit logs after the above change (if that's the case).
@varun-nf
