### ISSUE TITLE
ITCSTORE - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/Pre-production#204]
1. /on_search - /search timestamp is 16:28:07 and /on_search timestamp is 16:58:08 while /select timestamp is 16:28:52 - this means there's something wrong with your timestamp;
2. /on_search - items.price.maixmum_value is 0 while value is 225. value should be <= max value;
3. /on_search - what does fulfillment_id 1 mean? Consider static values for fulfillments as shown in API contract;
4. /on_select - items.fulfillment_id is not the same as fulfillment.id;
5. /on_confirm - items.fulfillment_id not available, quote.price is 73 but quote.breakup adds up to 123;
6. /on_status - items.fulfillment_id, fulfillment.id missing; also if values n/a don't include the keys instead of using the sample values from API contract (e.g. agent details),;
7. No API for /support, /on_support, /update, /on_update?

**Comment by BLR-0118** [comment]
@ITCStore - pls see feedback above. Also request you to submit logs in the right place: under logs, create a branch "ITCStore", add your logs to the branch & create PR

**Comment by ITCStore** [comment]
@BLR-0118 These are the steps we followed to submit the logs: https://github.com/ONDC-Official - > logs->create new fork -> after that we added logs files. Please let us know if we are doing anything wrong

**Comment by BLR-0118** [comment]
1. /on_init - payment type "ON-ORDER" and collected by "BAP" inappropriate here;
2. /on_status - should return the exact same thing as /on_confirm but with updated order state, fulfillment state and order value (in case of part return or cancel);
3. /on_confirm - order state is "Created" (means not auto-accepted?). Also base fulfillment state must be "Pending";

**Comment by BLR-0118** [comment]
@ITCStore

**Comment by BLR-0118** [comment]
ONDC Buyer App:
1. /on_init - quote.breakup.item.quantity.available.count and quote.breakup.item.quantity.maximum.count are not part of API contract;
2. /on_confirm - fulfillment.start.location.gps and fulfillment.end.location.gps are the same; fulfillment.start.instructions and fulfillment.end.instructions are meant to be the instructions for pickup & dropoff (can't be "Pending");
3. /on_status - same issues as in 1 & 2;
4. Will help if logs include both requests & responses as it will make it easy to correlate;

**Comment by BLR-0118** [comment]
@ITCStore

**Comment by BLR-0118** [comment]
Please also check your compliance with the checklist [here](https://docs.google.com/document/d/1jXkPwF-Fol9LeXbzQaC65R6UB60Cwc-cUiQ0qzsKNKQ/edit)

**Comment by BLR-0118** [comment]
1. /on_init - quote.breakup.price.value is integer for title_type "item" but string for "delivery". As per API contract, it should be string;
2. /on_confirm - not fully compliant with API contract. It should have complete fulfillment start address as well.
Request you to submit complete logs with Kotak buyer app & resubmit.

**Comment by BLR-0118** [comment]
@ITCStore

**Comment by BLR-0118** [comment]
1. /on_search - valid fssai no is of 14 digits and is required to be provided for f&b and packaged commodities only. The fssai no provided here is not reqd and not valid;
2. /on_confirm:
has a different transaction_id from /confirm, hence difficult to verify;
fulfillment state attrs used should be code, name (check the API contract);
payment params struct is missing;
3. /on_status: same issues with fulfillment state, payment params as on_confirm;

**Comment by BLR-0118** [comment]
4. Also, wanted to check - since your products are non-returnable, are you returning nack for /cancel?
5. Why can't you allow cancellation only for specific order states as documented in the api contract?

**Comment by BLR-0118** [comment]
@ITCStore

**Comment by BLR-0118** [comment]
Pls review the following:
1. /on_confirm & /on_status - address attributes for fulfillment/ billing are inconsistent. In some cases, door is " ", in other cases it's "null";
2. Pls document your compliance with [this](https://docs.google.com/document/d/1jXkPwF-Fol9LeXbzQaC65R6UB60Cwc-cUiQ0qzsKNKQ/edit)

**Comment by BLR-0118** [comment]
@ITCStore - no need to resubmit your logs but pls update on the above.

**Comment by ITCStore** [comment]
@BLR-0118 - on_status: fulfillment->billing->door parameter null replaced by empty string. will make it null so that it is consistent in both /on_confirm and /on_status requests. have gone through the checklist in the compliance link.
1.  search by item, category and city are enabled 2.currently instead of back images for packaged commodities we sending all details under different parameters of /on_search 3. Buyer App finder fee we are absorbing at our end and currently not passing to the customer. 4. No hardcoding of gateway end points. 5. Using states for Order & Fulfillment from the link shared. 6. Error codes we have tested for not serviceable, item not available
