### ISSUE TITLE
ZOHO - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/Pre-production#235]
for both retail & logistics, please submit logs for both request & response for all APIs (search, select, init - only for retail, confirm, status, update, cancel, support, track - if applicable);
@sarlarathnam

**Comment by BLR-0118** [comment]
Logs with mystore:
1. Context.timestamp should be in UTC;
2. /on_search - long_desc is string, you can't put html in it;
3. /on_search - decimal precision differences between value and maximum_value;
4. /on_select is not compliant with API contract (it shouldn't have payment/settlement terms);
5. /on_init - quote price doesn't add up to quote.breakup prices; also, how did order value suddenly change from 200 in /on_select to 206 in /on_init?
6. No APIs for update, cancel, support, track?

**Comment by BLR-0118** [comment]
@sarlarathnam

**Comment by sarlarathnam** [comment]
@BLR-0118 
1. We send timestamp in UTC Format. Can you please point to any file that has wrong timestamp. 
2, 3 . Will correct this
4. We will remove the additional nodes
5. The Tax component is not added to breakup. We will add it too. But tax details will be available only after init once we know the buyer's entire address. So total is possible to change after init, if the seller provides tax exclusive item prices in zoho. 
6. We are unable to test these with buyer apps. Facing different issues with each one. We will update once its resolved.

**Comment by BLR-0118** [comment]
Pls fix all issues mentioned above before resubmitting your logs

**Comment by BLR-0118** [comment]
@sarlarathnam

**Comment by BLR-0118** [comment]
Logistics logs with Grab:
1. /search - core_version should be "1.0.0"; empty keys should preferably not be sent;
2. /init - category_id is wrong (check API contract [here](https://docs.google.com/document/d/1LiKGK3AKwzx5GWAc5g942QKB-TzDn0gGMsvXNJgIrmk/edit) for valid fulfillment categories;
3. /confirm - not compliant with API contract;
4. /update - why is message_id same as order id? Not clear what's the use case for /update here?
Also, for all APIs above, there is a big difference between the request & response timestamps. Needs to be checked. Also, whether tracking is allowed or not depends on the logistics provider, not the logistics buyer.

**Comment by BLR-0118** [comment]
1. Logistics buyer app logs look ok;
2. Retail Seller app - can you pls resubmit logs with the pre-prod version of any of the prod apps (Kotak, mystore, Plotch)?
3. Pls confirm your compliance with this [checklist](https://docs.google.com/document/d/1jXkPwF-Fol9LeXbzQaC65R6UB60Cwc-cUiQ0qzsKNKQ/edit);

**Comment by sarlarathnam** [comment]
@BLR-0118 Prabhakar mentioned its okay if we submit reference apps logs. So we submitted with reference app. 
Also I'm trying to get hold of people from mystore or kotak. No responses yet. 
So looks like there is no proper working buyer app to test in pre-prod. Can you please let us know if there are any other buyer apps in pre-prod? 

We are targeting for go-live in this week. So would be great if you could assist us on this.

**Comment by BLR-0118** [comment]
Logs with ONDC ref buyer app:
1. /on_init - quote.price is different from /on_select All the breakup you show in /on_init should have been in /on_select;
2. /on_confirm - use the same order.id as in /confirm;
3. /on_confirm - order.state should be "Accepted", fulfillment.state.descriptor.code (not name) should be "Pending";
4. /on_confirm - payment.params, collected_by, etc. should be same as what's in /confirm;
5.  /on_status - should use one of the post-order fulfillment states (not Serviceable or Non-serviceable);

**Comment by BLR-0118** [comment]
@sarlarathnam

**Comment by sarlarathnam** [comment]
**/on_confirm - order.state should be "Accepted"**  Order state will be Accepted only once the seller has confirmed the order in Zoho Commerce application. I see that the case already discussed here https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit?disco=AAAAeLSMfeg We will sent Accepted in on_status only.

**Comment by BLR-0118** [comment]
Logs with mystore:
1. /on_select - no provider name (as in API contract)?
2. /on_init, /on_confirm, /on_status - buyer_app_finder_fee_amount is 0 even though there was a different value passed in /search;
3. /on_init, /on_confirm, /on_status - @ondc/org/settlement_details.settlement_counterparty should be "seller-app" as these are their settlement details;

**Comment by BLR-0118** [comment]
@sarlarathnam

**Comment by BLR-0118** [comment]
Can you pls confirm compliance with all the points in the checklist [here](https://docs.google.com/document/d/1jXkPwF-Fol9LeXbzQaC65R6UB60Cwc-cUiQ0qzsKNKQ/edit). Pls document your responses below.
