### ISSUE TITLE
DESIGNRIGHT - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/Pre-production#259]
Retail logs:
1. /on_search - descriptor.code is not as per API contract; all details need to be filled up for bpp/descriptor & bpp/providers as per the API contract [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit) and catalog mandatory requirements [here](https://docs.google.com/spreadsheets/d/1BNPOgcJzKglZzj1bpx-KkjvWBpH-R50AXbdC1AKJm1g/edit#gid=0);
2. /on_search - /search specifies fulfillment end location gps coords and /on_search returns a store which is much farther away even though the serviceability radius is defined as 5km. What's the logic that you're using to return catalog?
3. /select - not as per API contract, lots of additional attrs not in contract;
4. /on_select - F&B items also have a tax component which is not included here. Also check fulfillment.state & exactly what values need to be provided as per API contract;
5. /on_init - same issues as /on_select;
6. /on_confirm - pls comply with API contract (note there's no orderDate as mentioned here) and make sure all values as required by the API contract are provided in exactly the same form;
7. /on_cancel - should also return the cancellation_reason_id;
8. /on_status - many of the same issues as above; also, fulfillment state should have updated code; order.state shows "Completed" but fulfillment state shows "Serviceable" - not correct;
9. /on_track - when tracking is false in /on_confirm, what does track callback url mean?
10. No support, update APIs?

**Comment by BLR-0118** [comment]
Logistics:
1. /search, /init, /confirm - pls comply with the API contract [here](https://docs.google.com/document/d/1LiKGK3AKwzx5GWAc5g942QKB-TzDn0gGMsvXNJgIrmk/edit) "to the tee"
2. No link between item.id & fulfillment_id (as in retail)?

**Comment by BLR-0118** [comment]
Also, request you to submit logs for retail & logistics in separate folders.

**Comment by BLR-0118** [comment]
@NajeebMohammed

**Comment by NajeebMohammed** [comment]
> 2\. No link between item.id & fulfillment_id (as in retail)?

@BLR-0118  I didn't quite understand this point, can you explain? I dont see a link bewteen item.id and fulfillment_id in Logistics buyer&seller spec [here](https://docs.google.com/document/d/1LiKGK3AKwzx5GWAc5g942QKB-TzDn0gGMsvXNJgIrmk/edit#heading=h.isw251sl78pc)

**Comment by BLR-0118** [comment]
Retail logs:
1. unsolicited on_status - there's no "Agent-assigned" fulfillment state code. Please check the list of codes in /on_status; Also, order.state changes to "In-progress" when fulfillment state moves beyond "Pending";
Logistics logs:
2. on_search - valid fssai no is 14 digits;
1. /search - @ondc/org/payload_details - all values are integers;

**Comment by BLR-0118** [comment]
@NajeebMohammed

**Comment by BLR-0118** [comment]
pls also document your compliance with the checklist []([here](https://docs.google.com/document/d/1jXkPwF-Fol9LeXbzQaC65R6UB60Cwc-cUiQ0qzsKNKQ/edit))

**Comment by NajeebMohammed** [comment]
> Retail logs:
> 
> 1. unsolicited on_status - there's no "Agent-assigned" fulfillment state code. Please check the list of codes in /on_status; Also, order.state changes to "In-progress" when fulfillment state moves beyond "Pending";
>    Logistics logs:
> 2. on_search - valid fssai no is 14 digits;
> 3. /search - @ondc/org/payload_details - all values are integers;

1. Fixed
2. This is test data, when we onboard real customers on to prod we will have actual fssai number 
3. fixed

@BLR-0118  we can't send new set of logs as our logistics partner mystore have gone prod and dont have a working api in preprod currently. Please provide your approval to merge with production.
