### ISSUE TITLE
Getting error message "subscriber_id not whitelisted in our database"

### ISSUE THREAD

**Issue by rajat-patel-1** [ONDC-Official/Pre-production#261]
I tried to make a request on /subscribe endpoint with url: https://preprod.registry.ondc.org/ondc/subscribe
Getting error message :
`{
  "message": {
    "ack": {
      "status": "NACK"
    }
  },
  "error": {
    "type": "POLICY-ERROR",
    "code": "144",
    "path": null,
    "message": "The Subscriber id is not whitelisted in our database"
  }
}`

**Comment by rajat-patel-1** [comment]
@ONDC-Tech any solution for this ?

**Comment by vjku** [comment]
@rajat-patel-1 As shared [here](https://github.com/ONDC-Official/Pre-production/issues/18#issuecomment-1202820134) before whitelisting into preprod, we must provide a demo. Mr. Neeraj Jain mentioned [here](https://github.com/ONDC-Official/Pre-production/issues/3#issuecomment-1180300730) should be able to help once your app is demo'd.

First stage should be to complete staging onboarding. Go through [Tech Quickstart Guide.md](https://github.com/ONDC-Official/ONDC-Protocol-Specs/blob/master/protocol-specifications/docs/draft/Tech%20Quickstart%20Guide.md) and other docs at https://github.com/ONDC-Official/ONDC-Protocol-Specs/tree/master/protocol-specifications/docs/draft

**Comment by BLR-0118** [comment]
If you're not added to slack yet, pls email me - supriyo@ondc.org
