### ISSUE TITLE
Request for access to Staging Registry & Slack - Self Service Request

### ISSUE THREAD

**Issue by vjku** [ONDC-Official/Pre-production#264]
Hi,
Please help with access to staging registry and mobile app repo. Here is the [Onboarding JSON](https://ondc-dev.asap.in/staging/onboarding.json).

`{ "country": "IND", "city": "std:040", "type": "BPP", "subscriber_id": "https:\/\/ondc-dev.asap.in", "subscriber_url": "https:\/\/ondc-dev.asap.in", "domain": "nic2004:52110", "signing_public_key": "2sznQ6z8leNb+gOhvT3wvFjV1U5JBs4I4pLinQThNC0=", "encr_public_key": "06X9GBTquWkX0PVYUDj2JQherIFgGM+KVGmLJtR8E1A=", "created": "2022-10-04T05:56:52.470Z", "valid_from": "2022-10-04T05:56:52.470Z", "valid_until": "2023-11-09T05:56:52.470Z", "updated": "2022-10-04T13:15:58.349Z" }`

Sent an email with Onboarding JSON on 5th Oct 2022 to the following email addresses but got no response so far.

- meenakshi ~@~ ondc DOT org
- team ~@~ ondc DOT org
- tech  ~@~ ondc DOT org

Also help with Slack access to ondc ~@~ asap DOT in

It would save time if self-service access + periodical data reset similar to pre-prod /subscribe is available on staging without whitelisting.

@ONDC-Tech @BLR-0118 @sujeets-protean @jainneerajnj @primarypi

Thank you.

**Comment by BLR-0118** [comment]
Process for addition to staging registry is available [here](https://github.com/ONDC-Official/ONDC-Protocol-Specs/blob/master/protocol-specifications/docs/draft/Tech%20Quickstart%20Guide.md)

**Comment by vjku** [comment]
Thank you @BLR-0118 for the reply. I have prepared the [JSON](https://ondc-dev.asap.in/staging/onboarding.json) as per [this](https://docs.google.com/document/d/1HnOeTBWvYXO8kjAEHSrR6W8XICsPfKGIT6B_IhmvVV0) document but can not tag the registry team on Slack (Dhiraj Patorkar,  Bhakti Rana) as access to [ondc.slack.com](ondc.slack.com) is invitation only.

**Comment by BLR-0118** [comment]
pls connect with meenakshi@ondc.org

**Comment by vjku** [comment]
No luck, haven't got a reply to emails sent on 5th and 8th Oct to the following addresses.

meenakshi ~@~ ondc DOT org
team ~@~ ondc DOT org
tech ~@~ ondc DOT org

**Comment by BLR-0118** [comment]
can you email me - supriyo@ondc.org

**Comment by vjku** [comment]
@BLR-0118 Email sent.
