### ISSUE TITLE
NSTORE - Compliance Check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/Pre-production#54]
1. on_search - response has to have all mandatory attributes required for the catalog to be published as per [this](https://docs.google.com/spreadsheets/d/1BNPOgcJzKglZzj1bpx-KkjvWBpH-R50AXbdC1AKJm1g/edit#gid=0). There are several inconsistencies - category_id different for different items (it has to be exactly as specified), ttl of "P0" is not ISO8601 durations format, how can food items be returnable with return window of 48h?
2. Is search by city supported?
3. I don't see /select, /on_select with ONDC buyer app?
4. Logistics BAP - pls set core_version to 1.0.0
5. Please make sure your requests & responses are exactly compliant with the API contracts

**Comment by BLR-0118** [comment]
Also:
6. How many stores do you plan to onboard - only for F&B?
7. How many SKUs per store?

**Comment by BLR-0118** [comment]
@nstoretech

**Comment by Girisuta** [comment]
on_search - response has to have all mandatory attributes required for the catalog to be published as per this. There are several inconsistencies - category_id different for different items (it has to be exactly as specified), ttl of "P0" is not ISO8601 durations format, how can food items be returnable with return window of 48h?
(nStore) -  We had used the test data set up and hence the category id was different & returnable/cancellable with test data .  Returnable/Cancellable is merchant's prerogative and it is configurable at our end. We have now setup the data similar to Production and uploaded the latest logs. ttl is updated. 
I don't see /select, /on_select with ONDC buyer app?
(nStore) - Uploaded now
Logistics BAP - pls set core_version to 1.0.0
(nStore) - Updated and uploaded the recent logs
Please make sure your requests & responses are exactly compliant with the API contracts
(nStore) - It is complaint with the API document version 1.0.3 - https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit
(nStore) - Logistics Buyer & Seller Contract Version:0.97 - https://docs.google.com/document/d/1LiKGK3AKwzx5GWAc5g942QKB-TzDn0gGMsvXNJgIrmk/edit?usp=drivesdk
How many stores do you plan to onboard - only for F&B? 
(nStore) - We have Merchants for Grocery category in Bangalore for now. F&B in other cities.
How many SKUs per store?
(nStore) - Average of 995 SKUs per Grocery Store 
@BLR-0118

**Comment by Girisuta** [comment]
Is search by city supported? - Yes, but we are unable to upload logs for the same as none of the buyer app supports it . Kotak buyer app has issues

**Comment by BLR-0118** [comment]
Please check the [catalog compliance sheet](https://docs.google.com/spreadsheets/d/1BNPOgcJzKglZzj1bpx-KkjvWBpH-R50AXbdC1AKJm1g/edit#gid=0) and make sure you're in full compliance. Some areas where you aren't:
1. descriptor/provider/item needs to have short_desc & long_desc
2. category_id for grocery should be either "Packaged Commodities" or "Packaged Foods" as mentioned in the sheet

**Comment by BLR-0118** [comment]
@Girisuta

**Comment by BLR-0118** [comment]
also, check for search by city with Plotch.ai

**Comment by Girisuta** [comment]
Hi @BLR-0118 

We have resubmitted the logs , fixed wherever there were mismatch with the contract . Have posted the logs for Search by City separately which we tested with Kotak . Kindly review and let us know .

**Comment by Girisuta** [comment]
Hi @BLR-0118 , I need to make few more changes.  I will resubmit it by end of today and confirm. Kindly review the same after that.

**Comment by Girisuta** [comment]
Hi @BLR-0118 , We have uploaded the latest PR with the implementation as per contract.

**Comment by Girisuta** [comment]
Kindly review

**Comment by BLR-0118** [comment]
Retail:
1. /on_search - core_version should be "1.0.0" for all APIs;
2. /on_search - pls comply with the API contract - note there is no ttl in bpp/descriptor;
3. /on_search - how can the declared price (value) be greater than maximum_value?
4. /on_select, /on_init, /on_confirm, /on_status - pls check the API contract for what's there in order.provider;
5. /on_select - what does it mean to provide a TAT of 24 hrs and also say it's non-serviceable?
6. /on_status - there is no fulfillment type "SHIPPING";
7. /on_cancel - cancellation_reason_id should be exactly as specified in the [process flow doc](https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit);
8. search by city log - couldn't figure out if this should also be reviewed but there are several issues:
a. pls carefully check the category_id defined; there is no "Food" or "Beverage", there's only "F&B";
b. how can Dosa be returnable with return window of 24h?
c. there is a catalog item called "Delivery Charge" which is returnable. What does this mean?

Logistics:
I couldn't figure out which logistics bap logs to review. Logs shared are primarily for registry lookup and the Context of the search requests but couldn't find the message anywhere;

**Comment by BLR-0118** [comment]
@Girisuta

**Comment by BLR-0118** [comment]
@nstoretech

**Comment by Girisuta** [comment]
@BLR-0118 , We have submitted the latest logs for your review . We have fixed all the issues that you gave as feedback last time. Please find the comments inline for all the comments you mentioned last time : 
1. /on_search - core_version should be "1.0.0" for all APIs; - We have updated the same
2. /on_search - pls comply with the API contract - note there is no ttl in bpp/descriptor; - We have updated the same 
3. /on_search - how can the declared price (value) be greater than maximum_value? - Data issue fixed 
4. /on_select, /on_init, /on_confirm, /on_status - pls check the API contract for what's there in order.provider; - Incorporated as per the contract
5. /on_select - what does it mean to provide a TAT of 24 hrs and also say it's non-serviceable? - We have fixed as per your comments. Please clarify whether we should send/not send the mandatory data if it is non-serviceable. At present, we are sending all the mandatory data.  
6. /on_status - there is no fulfillment type "SHIPPING"; - Fixed 
7. /on_cancel - cancellation_reason_id should be exactly as specified in the process flow doc; - Fixed
8. search by city log - couldn't figure out if this should also be reviewed but there are several issues: - This was the old log. We have resubmitted the new log taken with Plotch.
a. pls carefully check the category_id defined; there is no "Food" or "Beverage", there's only "F&B"; - These are from old logs, we have fixed now 
b. how can Dosa be returnable with return window of 24h? - These are from our old logs, we have data equivalent to live.
c. there is a catalog item called "Delivery Charge" which is returnable. What does this mean? - This is an internal product, and it was showing up in old logs, it will not show up in the catalog in the latest logs. 

Logistics:
I couldn't figure out which logistics bap logs to review. Logs shared are primarily for registry lookup and the Context of the search requests but couldn't find the message anywhere; - There were logs uploaded by Shiprocket in our name as well and hence the confusion. Kindly check the ones uploaded today.

Note: As we have been discussing in the calls, order id is same across the flows. We are using the order id generated by the buyer app. 

Kindly review and let us know.

**Comment by Girisuta** [comment]
@BLR-0118

**Comment by BLR-0118** [comment]
Retail Seller:
1. All APIs - Context.ttl can't be more than 30s as defined in spec;
2. /on_init - there's no areaCode attr;
3. /on_confirm - there's no fulfillment state at this stage. Pls follow [these codes](https://github.com/ONDC-Official/ONDC-Protocol-Specs/issues/26) only;
4. How did the order.payment change between on_confirm and on_status?
5. /on_cancel - should comply with updated contract;
6. /on_update - no log?

Logistics Buyer:
1. /on_init - country is in fulfillment.start but not fulfillment.end;
2. /on_init - cod settlement window of "PT2D" is incorrect ISO8601 duration format (should be "P2D");
3.

**Comment by BLR-0118** [comment]
@Girisuta

**Comment by Girisuta** [comment]
@BLR-0118 
We have resubmitted the logs testing end to end with Plotch (Buyer app) and Shiprocket (Logistics)
https://github.com/ONDC-Official/Pre-production/pull/136

Response to your earlier comments : 
----------------------------------------

Retail Seller:
------------

1. All APIs - Context.ttl can't be more than 30s as defined in spec; - updated 
2. /on_init - there's no areaCode attr; - updated 
3. /on_confirm - there's no fulfillment state at this stage. Pls follow https://github.com/ONDC-Official/ONDC-Protocol-Specs/issues/26 only; - updated 
4. How did the order.payment change between on_confirm and on_status? - please check the latest log 
5. /on_cancel - should comply with updated contract; - Cancellable - N for all our products 
6. /on_update - no log? - Cancellable - N for all our products hence from Buyer app , they show non-cancelable and hence we have not uploaded the log. If there is any update call, we send NACK with policy error
{"status":"NACK"},"error":{"type":"POLICY-ERROR","code":"50002","message":"Cancel and Returns not supported"}}}

Logistics Buyer:
-------------------

1. /on_init - country is in fulfillment.start but not fulfillment.end; - updated 
2. /on_init - cod settlement window of "PT2D" is incorrect ISO8601 duration format (should be "P2D"); - updated 

Kindly review

**Comment by BLR-0118** [comment]
1. Retail seller app (BPP) logs are ok. Following points to be taken note of (logs not to be resubmitted):
a. /on_search - shows Quaker Oats (packaged commodity). The declared price includes tax and tax is not a separate quote breakup item for any category (except F&B);
b. Back images to be made available for all grocery items in Prod;
2. Logistics BAP:
a. No ttl in Context for any API;
b. on_init - quote for item selected is twice what's shown in on_search;
2 has to be fixed and log resubmitted;

**Comment by BLR-0118** [comment]
@Girisuta

**Comment by Girisuta** [comment]
Hi @BLR-0118 

Logistics BAP:
b. on_init - quote for item selected is twice what's shown in on_search;

As discussed with Shiprocket team, it is not an issue. 
From on_search , we have selected  id : 107 & the data as in log : 
"items": [
            {
              "id": "107",
              "descriptor": {
                "name": "Same Day Delivery",
                "short_desc": "Same Day Delivery",
                "long_desc": "Same Day Delivery"
              },
              "price": {
                "currency": "INR",
                "value": "105.4"
              },
              "category_id": "Same Day Delivery"
            }
          ]

On_init response from Logistics : 
"order": {
      "provider": {
        "id": "107"
      },
      "provider_location": {
        "id": "SR-Location"
      },
      "items": [
        {
          "id": "107"
        }
      ],
      "quote": {
        "price": {
          "currency": "INR",
          **"value": "210.8"**
        },
        "breakup": [
          {
            "@ondc/org/item_id": "107",
            "@ondc/org/title_type": **"Delivery Charge"**,
            "price": {
              "currency": "INR",
              **"value": "105.4"**
            }
          },
          {
            "@ondc/org/title_type": "RTO Charge",
            "title": **"RTO Charges",**
            "price": {
              "currency": "INR",
              **"value": "105.4"**
            }
          }

As higlighted in the above breakup, they are sending additional RTO charge which is not to be fixed at our end. 
If required, we can have a three way call between us to sort it out .

**Comment by Girisuta** [comment]
Hi @BLR-0118 ,

We have resubmitted the logs for Logistics BAP:
b. on_init - quote for item selected is twice what's shown in on_search;

We got the fix from shiprocket and resubmitted our logs. Kindly review.

**Comment by BLR-0118** [comment]
Retail Seller App:
1. /on_select - fulfillment TAT & category not provided?
2. /on_status - there's no billing.gps

**Comment by BLR-0118** [comment]
Logistics Buyer:
1. No /support API?

**Comment by BLR-0118** [comment]
@Girisuta

**Comment by Girisuta** [comment]
Hi @BLR-0118 

Retail Seller App:

/on_select - fulfillment TAT & category not provided? - As we had discussed earlier, we have provided the flexibility our merchants to use either self or call Logistics from Seller app and not from buyer app. Hence we have not provided these details. 
/on_status - there's no billing.gps - updated
No /update - even though return & cancel not allowed, you should be returning nack + error code in /update - updated

Logistics Buyer:

No /support API? - updated

**Comment by BLR-0118** [comment]
1. /on_search - why is search for "oats" returning "udhaiyam moong dal"?
2. /on_select - fulfillments provider, category, TAT has to be filled up. If self-fulfilled, you can enter the name of merchant fulfilling the order;
3. /on_select - declared price is 160 but this is now broken up into item price & tax. This isn't correct. For groceries, the declared price is tax inclusive, so it should match the price in the quote;
4. /on_confirm - total quote is 160 but not clear why payment is showing 176?
5. /on_confirm - if BPP is collecting payment, settlement details should be for the buyer app since seller app has to settle with them;
6. /on_status - this shows payment as 160 whereas on_confirm shows 176. Why?
7. Also, /on_status should return an order trail in cases of returns & cancels, where it should also show those items returned & cancelled as well.

**Comment by BLR-0118** [comment]
@Girisuta

**Comment by BLR-0118** [comment]
Logistics BAP - looks ok. Shiprocket needs to fix that issue with the RTO charges not being included in the catalog declared price itself.

**Comment by Girisuta** [comment]
Hi @BLR-0118 ,

We have resubmitted the retail logs: 
https://github.com/ONDC-Official/Pre-production/pull/171

/on_search - why is search for "oats" returning "udhaiyam moong dal"? - This was the Data issue . We submitted the logs for Udhaiyam Moon dhal. Resubmitted with appropriate data.
/on_select - fulfillments provider, category, TAT has to be filled up. If self-fulfilled, you can enter the name of merchant fulfilling the order; - We have updated the same. For Self, we are not passing the category as our understanding is that  category is required to be passed by the Logistics provider. 
/on_select - declared price is 160 but this is now broken up into item price & tax. This isn't correct. For groceries, the declared price is tax inclusive, so it should match the price in the quote; - Data issue in logs , resubmitted
/on_confirm - total quote is 160 but not clear why payment is showing 176? - resubmitted
/on_confirm - if BPP is collecting payment, settlement details should be for the buyer app since seller app has to settle with them; - resubmitted 
/on_status - this shows payment as 160 whereas on_confirm shows 176. Why? - Resubmitted 
Also, /on_status should return an order trail in cases of returns & cancels, where it should also show those items returned & cancelled as well. - Return and Cancel is set to N for out products , please confirm if this is applicable for us

**Comment by BLR-0118** [comment]
1. /search is for fulfillment end location with specified gps coords. /on_search returns response for a provider which has location at different gps coords but serviceability radius of 200m. How's this possible? Also, please note that the only radius unit supported for now is "km";
2. /select - item id is 106 which isn't in /on_search;
3. /on_init - why is settlement counterparty buyer app? In /on_init, the seller app is expected to send their settlement details if payment is collected by buyer app;
4. /on_confirm - pls update with the latest order state as per the API contract;
5. /on_status - order & fulfillment state should be as per the API contract. Also, the quote breakup is different from what's in /on_select & /on_confirm;
6. /on_update - if you're not supporting returns, NACK & error code should be returned in /update itself. Pls note that ACK/NACK are sync responses;

**Comment by BLR-0118** [comment]
@Girisuta

**Comment by Girisuta** [comment]
@BLR-0118 - We have resubmitted the retail logs : 
https://github.com/ONDC-Official/Pre-production/pull/189
Kindly review

**Comment by BLR-0118** [comment]
1. /on_search - what's the difference between fulfillment_id 3 & 4?
2. /on_select - item id 101 (value of 1) is selected and in quote this value is broken up into item price & tax. This isn't correct;
3. /on_init, /on_confirm - settlement details => need not include the null key values;
@Girisuta

**Comment by Girisuta** [comment]
/on_search - what's the difference between fulfillment_id 3 & 4? 
"bpp/fulfillments": [
        {
          "id": "1",
          "type": "Delivery"
        },
        {
          "id": "2",
          "type": "Pickup"
        },
        {
          "id": "3",
          "type": "home-delivery"
        },
        {
          "id": "4",
          "type": "HOME-DELIVERY"
        }
      ]
This 3 & 4 are expected like the above for our products to be listed on the Reference buyer app and hence we pass it like the above.  It is not an issue on our side. 

/on_select - item id 101 (value of 1) is selected and in quote this value is broken up into item price & tax. This isn't correct;
We pass the Quote breakup of price and tax in the quote. We added Re.1 product to check the prepaid as plotch points to Live gateway . Please let us know what is incorrect in this . 

/on_init, /on_confirm - settlement details => need not include the null key values;
We will remove the null values , do we need to resubmit for this. Kindly confirm .

@BLR-0118

**Comment by BLR-0118** [comment]
Pls make these 2 changes. No need to resubmit logs.
1. /on_init - payment_collected_by="BAP" should come from the BAP's request e.g. /init. If it comes in /on_init, it should be "BPP";
2. /on_status - order.created_at is missing even though it was there in /on_confirm.

**Comment by BLR-0118** [comment]
@Girisuta
