### ISSUE TITLE
SHIPROCKET - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/Pre-production#55]
1. on_search - in some cases, short_desc & long_desc are empty for some providers. This has to be filled up.
2. on_search - there are so many providers each of whom has the same turnaround time of 45 mins but different prices. Is this using dummy data - just curious;
3. on_init - quote.breakup should have item_id for "Delivery Charge", otherwise how will the logistics buyer know if it matches the option they selected?
4. on_init - all prices are empty. Shouldn't it reflect the same price as shown to the logistics buyer in on_search?
5. on_confirm - order id (for the network) is generated by logistics buyer. However, your order id is different from the order id in /confirm.
6. /on_confirm - locations.id, provider.id are empty, category_id should be for the logistics (not retail or other payload);
7. /on_confirm - fulfillments start & end time slot shows TAT of 24 hrs but on_search showed 45 mins. Why the disconnect?
8. /on_cancel - not compliant with API contract [here](https://docs.google.com/document/d/1LiKGK3AKwzx5GWAc5g942QKB-TzDn0gGMsvXNJgIrmk/edit).
9. /on_update - this can be used to update the fulfillment start time slot, agent name, vehicle details, etc.
10. request not to send empty attributes for any response;
11. Change core_version to 1.0.0 for all responses;

**Comment by BLR-0118** [comment]
@keshav-BFRS01751

**Comment by keshav-BFRS01751** [comment]
About recommendation in point no (9) 

As per the discussion "agent name, vehicle details" will not be the mandatory attributes. Because courier partners are not providing those informations.

**Comment by keshav-BFRS01751** [comment]
Generate the PR. 
https://github.com/Open-network-for-digital-commerce/Pre-production/pull/77

**Comment by BLR-0118** [comment]
1. No RTO fulfillment record created in /on_confirm?

**Comment by BLR-0118** [comment]
@keshav-BFRS01751

**Comment by keshav-BFRS01751** [comment]
There are two attributes in /on_confirm request json
1. date time Range : It is option as mentioned in contract doc. I am attaching the screen shoots
2. Agent details : This attribute is also optional as per the discussion with @BLR-0118 (Supriyo) & Shiprocket product team, because courier partner is not providing the agent name and vehicle detail every time
<img width="1440" alt="Screenshot 2022-08-22 at 8 42 00 AM" src="https://user-images.githubusercontent.com/101786773/186043193-6158294f-22dc-407e-b2bf-9fe8fece1187.png">
.

**Comment by BLR-0118** [comment]
Pls update error code in /on_cancel to the newly created error code.
Logs are compliant with API contract
@keshav-BFRS01751
