### ISSUE TITLE
PLOTCH.AI - COMPLIANCE CHECK

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/Pre-production#61]
1. Context should have core_version of "1.0.0" for all requests
2. The 3 search requests use 2 separate bap end points. Are all 3 search requests working for all the bap end points?
3. search_category_name, search_city, search_item_id, search_product_name all have the same transaction_id & timestamp. Transaction_id is understandable but same timestamp?
4. init - payment - type is post-fulfillment, collected by "BAP". How? Typically on-fulfillment or post-fulfillment, is for CoD but won't be collected by BAP. Pls clarify what type of payment this is?
5. You don't have /update?

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by vikramacharya** [comment]
Context should have core_version of "1.0.0" for all requests - Made the changes.
The 3 search requests use 2 separate bap endpoints. Are all 3 search requests working for all the bap endpoints? - Yes it is working for all.
search_category_name, search_city, search_item_id, and search_product_name all have the same transaction_id & timestamp. Transaction_id is understandable but the same timestamp? It was done during the test. Will push the updated log of search in PR.
init - payment - type is post-fulfillment, collected by "BAP". How? Typically on-fulfillment or post-fulfillment, is for CoD but won't be collected by BAP. Pls clarify what type of payment this is? - BAP is collecting payment in our case. Have sent the confirm log for prepaid. 
You don't have /update? - Yes, we have the update. Update payload for return flow is in progress. Will share the same in log.

**Comment by BLR-0118** [comment]
@vikramacharya - checked your log for 4 above. looks ok.

**Comment by vikramacharya** [comment]
/update log added - https://github.com/Open-network-for-digital-commerce/Pre-production/pull/78

**Comment by BLR-0118** [comment]
1. /update - pls check the following:
image is blank but is mandatory;
ttl_reverseqc shows "PT3D"; the actual ISO8601 duration format is "P3D";
2. for all other API requests (other than /search), I couldn't see a bpp_id/bpp_uri. With which bpp was the complete flow completed? Can you also share some responses from /on_search onwards that were used to complete the entire order flow?

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by vikramacharya** [comment]
1. /update  - We have corrected them. As of now few BPPs support this but they are on staging. 

2. for all other API requests (other than /search), I couldn't see a bpp_id/bpp_uri. With which bpp was the complete flow completed? Can you also share some responses from /on_search onwards that were used to complete the entire order flow?
- Below are the Logs submitted by the BPPs with whom we have done the end-to-end order flow test.

- Testing Logs with Petpooja
https://github.com/craftsvilla/plotch/tree/main/logs/Petpooja/Testing-with-Plotch

- Testing Logs with Uengage
https://github.com/craftsvilla/plotch/tree/main/logs/uengage/plotch-logs

- Testing Logs with Bizom
https://github.com/craftsvilla/plotch/tree/main/logs/bizom-logs/plotch

**Comment by BLR-0118** [comment]
You also need a bpp_id/bpp_uri in Context which identifies the sellerapp with which you're transacting.
@vikramacharya

**Comment by vikramacharya** [comment]
Added bpp_id in the context. Also, these are the latest logs with Uengage:
https://github.com/Open-network-for-digital-commerce/Pre-production/pull/82/files

**Comment by BLR-0118** [comment]
1. Context for all APIs (except /search) should show both bpp_id, bpp_uri. bpp_id is now there but not bpp_uri;
2. The order id for /track, /update is different from the order id in /confirm. Is this not from uengage?

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by vikramacharya** [comment]
@BLR-0118 
1. We thought either pf bpp_id/bpp_uri was required. Will add bpp_uri in context as well. 
2. Order ID for /track and /update is same. Attached is the screenshot from the log.

<img width="1277" alt="Screenshot 2022-08-23 at 10 19 49 AM" src="https://user-images.githubusercontent.com/1625240/186072509-ca6473ab-6b24-46aa-a37e-2f5fb8869275.png">
<img width="1135" alt="Screenshot 2022-08-23 at 10 19 39 AM" src="https://user-images.githubusercontent.com/1625240/186072525-f5116c52-8638-47e3-a284-6653bc8fdb27.png">
<img width="1083" alt="Screenshot 2022-08-23 at 10 19 24 AM" src="https://user-images.githubusercontent.com/1625240/186072529-a7472185-f792-4416-aa98-06db05f6d472.png">
<img width="1261" alt="Screenshot 2022-08-23 at 10 20 01 AM" src="https://user-images.githubusercontent.com/1625240/186072536-c9b3d41b-4499-47c0-93b0-ad8ac34333fa.png">

**Comment by ONDC-Tech** [comment]
why can't you use the same order id in /confirm, /track, /update?

**Comment by vikramacharya** [comment]
It's the same @ONDC-Tech. Please correct me if I am reading this wrong. I have highlighted the order IDs in the above screenshots. All transactions have the same order ID.

**Comment by BLR-0118** [comment]
1. Context for some of the APIs still don't have bpp_id/bpp_uri e.g. /status. Every API other than /search should have this. Can you pls check once?
2. /update - can you pls fix it so it's compliant with the latest contract?
Pls submit logs only for the above changes.

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by vikramacharya** [comment]
@BLR-0118 - We have made the necessary changes in the payload. 
Ref PR: https://github.com/Open-network-for-digital-commerce/Pre-production/pull/102/files

**Comment by ONDC-Tech** [comment]
/support.ref_id is the same as /status.order_id. However, the API contract mentions that /support.ref_id should be the transaction_id.
@vikramacharya

**Comment by vikramacharya** [comment]
@ONDC-Tech - Changed the same to the transaction ID. 
https://github.com/ONDC-Official/Pre-production/pull/103
