### ISSUE TITLE
FLIPKART - Compliance Check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/Pre-production#62]
1. on_search shouldn't have gateway id / uri in bpp_id/bpp_uri of Context
2. on_search Context seems to be copied from search Context including timestamp. This isn't correct.
3. on_init is not compliant with the API contract []([here](https://docs.google.com/document/d/1LiKGK3AKwzx5GWAc5g942QKB-TzDn0gGMsvXNJgIrmk/edit))
4. on_cancel, on_status should be compliant with the API contract linked above.
5. Different order & fulfillment states are [here](https://github.com/Open-network-for-digital-commerce/ONDC-Protocol-Specs/issues/26) and should be strictly followed.
6. Do you support unsolicited on_cancel, on_status calls?

**Comment by BLR-0118** [comment]
@sakamotojin

**Comment by BLR-0118** [comment]
7. You're not supporting update requests and the tag for ready to ship as per the update API contract?

**Comment by sakamotojin** [comment]
**Updates**  
-     [1-5]  => Issues fixed will update the logs and raise a new PR 
-     [6]  => As of now we are planning to handle this via ops . we will take the automation tasks in the upcoming sprints
-     [7]  => WIP

**Comment by sakamotojin** [comment]
[Updated Logs](https://github.com/Open-network-for-digital-commerce/Pre-production/pull/76)

**Comment by BLR-0118** [comment]
1. /on_confirm - should use the same order id from /confirm. You can't create a new order id;
2. /on_update - when will this be available?

**Comment by BLR-0118** [comment]
@sakamotojin

**Comment by sakamotojin** [comment]
1.  /on_confirm - should use the same order id from /confirm. You can't create a new order id;
**Updated the Logic, will update the logs on Monday**

2. /on_update - when will this be available?
**We have implemented this, Will Update the Logs On Monday Post Testing**

**Comment by BLR-0118** [comment]
1. /on_update doesn't have the bpp_id, bpp_uri
2. ttl of "PT1D" is not correct ISO8601 duration format. It should be "P1D"

**Comment by sudheep2** [comment]
@BLR-0118 updated logs
