### ISSUE TITLE
Bizom - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/Pre-production#63]
General comments:
1. The entire context from response seems to be copied from request including timestamp. This is incorrect.
2. Catalog (on_search) response should be exactly compliant with [this](https://docs.google.com/spreadsheets/d/1BNPOgcJzKglZzj1bpx-KkjvWBpH-R50AXbdC1AKJm1g/edit#gid=0).
3. Please comply with API contracts for [retail](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit) & [logistics](https://docs.google.com/document/d/1LiKGK3AKwzx5GWAc5g942QKB-TzDn0gGMsvXNJgIrmk/edit) as defined.
4. I don't see any update or cancel APIs being supported?

**Comment by BLR-0118** [comment]
@samarthpatel-bizom

**Comment by BLR-0118** [comment]
From updated logs submitted on 18/8:
1. /on_search - bpp/providers.locations.id isn't matching location_id for item;
2. /on_search - no category_id for item;
3. /on_init - quote.breakup shouldn't have item id for non-products; for products, the item id is expected to match the item id sent in /select (applies to other APIs where quote.breakup is used);
4. logistics /on_search - pls check the logistics API contract - for fulfillments, you need to send the start & end gps coordinates & pin code only, not the fulfillment address;
Request you to separate out the retail & logistics logs to make it easy for us to verify;

**Comment by BLR-0118** [comment]
@samarthpatel-bizom

**Comment by samarthpatel-bizom** [comment]
In ref to point 4- I believe doc specifies the mandatory requirements but why can't we send other parameters of the object also ?

**Comment by BLR-0118** [comment]
This is actually a privacy issue. You should only send it to the provider who'll be fulfilling the order; hence, this data is sent in the /init request.

**Comment by BLR-0118** [comment]
@samarthpatel-bizom

**Comment by samarthpatel-bizom** [comment]
Ok got it. So in other APIs i can send but not in search.

**Comment by BLR-0118** [comment]
1. Logistics logs - don't see bpp_id, bpp_uri for requests after /search;
2. ttl of "PT2D" or "PT1D" is incorrect ISO8601 duration format. It should be "P2D" or "P1D";
3. why are you returning items array in /on_select? This is not a part of the API contract and will confuse the buyer app.

**Comment by BLR-0118** [comment]
@samarthpatel-bizom

**Comment by samarthpatel-bizom** [comment]
@BLR-0118  isn't item array part of contract ? 
`"items":
[
{
"fulfillment_id": "Fulfillment1",
"id": "18275-ONDC-1-9",
}
],
`

**Comment by samarthpatel-bizom** [comment]
@BLR-0118  we have submitted the updated logs please check.

**Comment by BLR-0118** [comment]
1. /on_search - short_desc & long_desc missing for 1 item;
2. /on_search - your catalog seems to be primarily choco bars & similar items. Hence, it should come under packaged foods and you should provide the [statutory reqs](https://docs.google.com/spreadsheets/d/1BNPOgcJzKglZzj1bpx-KkjvWBpH-R50AXbdC1AKJm1g/edit#gid=0) for packaged foods including veg/non-veg;
3. How did the finder_fee_amount in payment change between /on_init and /on_confirm?
4. /on_status - there is no fulfilment state "Created". Check the updated list []([here](https://github.com/ONDC-Official/ONDC-Protocol-Specs/issues/26);)
5. /on_cancel - should comply with updated API contract;
6. /on_update - no logs?

**Comment by BLR-0118** [comment]
@samarthpatel-bizom

**Comment by BLR-0118** [comment]
Logistics buyer:
1. no /update?

**Comment by BLR-0118** [comment]
Also, for retail seller app, hope you're supporting search by category & city?

**Comment by samarthpatel-bizom** [comment]
Yes we are supporting search by category and city.
For point 3. In the logs i can't see any amount changing between on_init and on_confirm.

@BLR-0118

**Comment by samarthpatel-bizom** [comment]
- /on_search - short_desc & long_desc missing for 1 item - all descriptions will be available on live.  For now, we will delete the item that does not have the description

- /on_search - your catalog seems to be primarily choco bars & similar items. Hence, it should come under packaged foods and you should provide the statutory reqs for packaged foods including veg/non-veg; - on live all images (front & back) will be available.  As this is a tedious process and will have to be re-done on our live env, we will do this activity once we move to live.  We have added images for 2-3 SKUs for reference purposes.  We will add the veg symbol for all our products 

- /on_update - no logs? - we are send a nach for all refunds today as none of the current products are returnable.  We will ensure the current error code is shared with this NACK response.

@BLR-0118

**Comment by BLR-0118** [comment]
1. /on_search log is empty.
2. Can you pls add the logs for the buyer app request also - /search, /select, etc.
3. Also, pls add logs for /support, /track, /update & their callbacks

**Comment by BLR-0118** [comment]
@samarthpatel-bizom

**Comment by BLR-0118** [comment]
1. /on_search - category should be packaged commodity or packaged food or fruits & vegetables as per this [sheet](https://docs.google.com/spreadsheets/d/1BNPOgcJzKglZzj1bpx-KkjvWBpH-R50AXbdC1AKJm1g/edit#gid=0)
2. Can we pls have 1 end-to-end flow only for search, select, init, confirm? Rest APIs are ok.

**Comment by BLR-0118** [comment]
@samarthpatel-bizom

**Comment by BLR-0118** [comment]
1. Retail Seller App:
a. item 119 in /on_search - price is 332.69, in /on_select it's 332. Why this rounding diff?
b. No ttl in Context for any API;
@samarthpatel-bizom

**Comment by samarthpatel-bizom** [comment]
@BLR-0118  there isn't any ttl in context on callback apis as per doc.  Pls let me know if it needs to be added or not.  And for point 1, we have done rounding off will remove that.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/109139902/188815666-e5364c83-ec9c-4777-badc-03d0f9d93cb2.png">

**Comment by BLR-0118** [comment]
Retail Seller App:
1. In one of the items, short_desc & long_desc are missing. Even if missing for 1 item, many buyer apps will reject the entire catalog. A better option for you may be to remove this item from the catalog if this desc is not available;
Logistics Seller App:
1. If you're using "Same Day Delivery", you need to trigger the "ready to ship" through /update. This API is not available.
@samarthpatel-bizom

**Comment by BLR-0118** [comment]
1. still not fixed. You need to take care of this. Don't need to resubmit logs.
@samarthpatel-bizom
