### ISSUE TITLE
eVitalRx - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/Pre-production#68]
1. Please be compliant with the following "to a tee":
a. Catalog compliance requirements [here](https://docs.google.com/spreadsheets/d/1BNPOgcJzKglZzj1bpx-KkjvWBpH-R50AXbdC1AKJm1g/edit#gid=0)
b. Retail API contract [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit)
2. Please check the technical checklist in the pinned messages for ondc-cohort-2 slack channel for which I've sent you an invite
3. You need to implement APIs for update, cancel, status, track, support.
4. In /on_confirm, you're generating a separate order.id. This will be generated by the buyer app and needs to be reused by the seller app.
5. How are you planning fulfillments - on-network logistics (in which case you need to test logistics integration as per this [API contract](https://docs.google.com/document/d/1LiKGK3AKwzx5GWAc5g942QKB-TzDn0gGMsvXNJgIrmk/edit)) or self-delivery.

**Comment by BLR-0118** [comment]
@evital-manav

**Comment by BLR-0118** [comment]
1. /on_search - Context.ttl should be "PT30S";
2. /on_search - ids for item, location, provider look like hashes - "caaW7GcXGRvkJ93wd0O5XQ=="? You can simplify it;
3. /on_search - duplicate images - https://d1tu4pmhr82np8.cloudfront.net/storage/chemists/thumb/default.jpg;
4. /on_search - this looks out of place - "@ondc/org/available_on_cod": true (line 137);
5. transaction_id for select & init are different. We need an end-to-end order with the same transaction_id for all APIs (except search);
6. /on_status - not compliant with API contract;
7. /on_track - when tracking is false, how is tracking url being provided?

**Comment by BLR-0118** [comment]
@evital-manav

**Comment by evital-manav** [comment]
2. We have a flow that all ids, which go outside the system are encrypted, that's not only for ONDC but for all the APIs we provide.
5. transaction_ids are provided by Buyer App (Plotch), They are sending different transaction_id for /select and /init.

Working on 1, 3, 4, 6, and 7, and will update soon.

**Comment by evital-manav** [comment]
logs updated @BLR-0118 sir.

**Comment by BLR-0118** [comment]
1. /on_search & other APIs - core_version should be "1.0.0";
2. /on_search - preferably, provider_id & location_id should be different. What if a provider is in multiple locations? Also, just curious how're you generating these ids?
3. /on_select - if fulfillment category is "Immediate Delivery", why's TAT 1 day?
4. /on_select - no delivery or other fulfillment charges?
5. /on_init - item available/max count could be given in /on_select but not in /on_init as per the contract;
6. /on_init - the payment block is not correct and it changes in /on_confirm (to BPP collecting payment post-fulfillment, which is correct). Why should the seller app propose "BAP" collecting payment?
7. /on_cancel - not as per contract;
8. /on_track - since tracking is "false" in /on_confirm, the status should be inactive;
9. No /on_update? Since you don't support return, you should be returning NACK + error code in /update;

**Comment by BLR-0118** [comment]
@evital-manav

**Comment by evital-manav** [comment]
2. we have a unique provider_id for provider-location-wise. the ids are just simple SQL ids, we encrypt them with AES encryption.
4. we have a minimum order value seller-wise, if the total quote exceeds it, then no delivery charges will be applied, if the total quote does not exceed it, then the charges will be applicable.

will update the logs soon for the rest of the issues. @BLR-0118 sir

**Comment by BLR-0118** [comment]
1. /init - payment block isn't appropriate here. If type = "POST-FULFILLMENT" it will be proposed by seller app (collected_by="BPP"), hence it should come in /on_init. In that case, buyer app will send their settlement details in /confirm. If buyer app collects payment (pre-paid), the payment block will be in /confirm (collected_by="BAP", type="ON-ORDER"). In your case, seller app is collecting payment and also sending their settlement details, which is incorrect. Suggest, you stick to the payment format for pre-paid which will be enabled for go-live (in this case, you send your settlement details as in /on_init and buyer app collects payment & send confirmation details in /confirm);
2. /confirm & /on_confirm should also have the settlement details ("@ondc/org/settlement_details");
3. /on_status - why don't you show the status of the same order created in /confirm?
4. /update - if you're returning NACK, it should be in /update (as NACK/ACK is synchronous call);
5.

**Comment by BLR-0118** [comment]
@evital-manav

**Comment by evital-manav** [comment]
logs updated @BLR-0118 sir.

**Comment by BLR-0118** [comment]
1. /on_select - TAT of "PT1D" is invalid, should be "P1D";
2. /init - fulfillment end address is Bangalore but gps is of Ahmedabad;
3. /cancel - your comment that buyer app 1 & 2 don't call /cancel because "it is mentioned that order items are not cancellable" - pls note the order can be cancelled before it has shipped. Hence, the above comment is not valid;
4. /on_status - there is no fulfillment state "Pending". Pls check here for the list of [order & fulfillment states](https://github.com/ONDC-Official/ONDC-Protocol-Specs/issues/26);

**Comment by BLR-0118** [comment]
@evital-manav

**Comment by evital-manav** [comment]
3. We support the cancellation of the order before it is shipped, but the button is disabled from the buyer's side. I guess they should have enabled the button before they get the status 'shipped' of the order.

updating the rest of the issues, and will update the logs soon. @BLR-0118 sir.

**Comment by evital-manav** [comment]
logs updated @BLR-0118

**Comment by BLR-0118** [comment]
1. /confirm created an order for item id 8XlTP5Mglr1MTvN3AwE7Aw==. When status is called for the same order, it gives a different item id EyiaCqM4v561ZBZoJ9Qapg==. Why?
2. /on_status - typically, this is called when the fulfillment state has been updated. You should use one of the states as per the updated enums in the contract;
3. /update - uses a different order id from what's in /confirm, hence difficult to find out whether the part return flow & refund settlement details are correct;
4. Pls also test /cancel & /on_cancel & add to logs;

**Comment by BLR-0118** [comment]
@evital-manav

**Comment by evital-manav** [comment]
1. It was internal issue, solved in this PR and solved rest of the issues and updated the logs. @BLR-0118 sir.

**Comment by BLR-0118** [comment]
1. /on_select - not compliant with API contract - check items - contract only has id, fulfillment_id but your response has several other attrs;
2. /on_confirm - use the updated order state "Accepted" if it's auto-accept;

**Comment by BLR-0118** [comment]
@evital-manav

**Comment by evital-manav** [comment]
2. its not /auto_accept. corrected 1 and updated the logs.

**Comment by BLR-0118** [comment]
1. /on_select - ttl of "P1H" is wrong, it should be "PT1H" (for 1 hr) and "P1D" (for 1 day)

**Comment by BLR-0118** [comment]
@evital-manav

**Comment by evital-manav** [comment]
updated logs @BLR-0118 sir.

**Comment by BLR-0118** [comment]
1. /on_confirm - order state is "Created", not "Accepted" => does this imply that orders aren't auto-accepted?
2. /on_confirm - should have the settlement details sent in /on_init;
3. /on_confirm - fulfillment state should be set to "Pending";

**Comment by BLR-0118** [comment]
@evital-manav

**Comment by evital-manav** [comment]
1. orders are not auto-accepted.
2. orders mode was COD, buyer app is not sending settlement details.
Updated the logs with rest of issues. @BLR-0118 sir.

**Comment by BLR-0118** [comment]
I'm clearing your logs but pls take care of these 2 things:
1. How's a search for "Aata" returning "Navratna"?
2. In /on_confirm, the order should have created_at and updated_at and the same should be returned in /on_status, /on_update (if you allow update of order)
@evital-manav

**Comment by evital-manav** [comment]
1. I apologize, two searches were mixed from the logs. you can see different transaction_ids in /search and /on_search, I will correct the /search request log.
2. we don't support update, adding in /on_confirm and /on_status and updating the logs.
