### ISSUE TITLE
UENGAGE - Compliance Check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/Pre-production#80]
1. /on_search & other APIs - Context.timestamp can't be the same as what's in /search;
2. /on_search - following attributes for item are missing - category_id, fulfillment_id, contact_details_consumer_care (pls check the attrs from the API contract [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit);
3. /on_search - values for following are not standard (ISO8601 Duration) - return_window (which need not be provided for non-returnable items), time_to_ship;
4. /on_search - no ttl for Provider;
5. /on_search - tags added to items are not part of API contract;
6. /on_select - not as per API contract;
7. /on_select - quote.breakup should have item_id only for selected items (not services like taxes, delivery charges, etc.); also no quantity;
8. /on_init, /on_confirm - should be exactly compliant with the API contract (e.g. item attributes like returnable, etc are not in the contract, no ttl in the contract, etc.);
9. /on_status - don't see a value for fulfillment state;
10. /on_update - if your items are non-returnable, you should return NACK similar to /on_cancel

**Comment by BLR-0118** [comment]
same issues with Plotch buyer app as well
@shubhamuengage

**Comment by BLR-0118** [comment]
Also, when you're specifying FSSAI license no, it should be the exact 14 digit license no with no further prefixes
@shubhamuengage

**Comment by BLR-0118** [comment]
1. In /on_search, bpp_uri is "https://ondc.uengage.in/ondc/on_search". The buyer app is supposed to construct the endpoint by appending the action (API name) with this URI. In this case, is your endpoint "https://ondc.uengage.in/ondc/on_search/on_search"?
2. ttl of "P60M" is incorrect ISO8601 duration format. It should be "PT60M";
3. what does this mean in /on_search:
 "bpp/fulfillments": [
                    {
                        "id": "89",
                        "type": "Pickup",
                        "@ondc/org/category": "F&B",
                        "@ondc/org/TAT": "PT24H",
                        "provider_id": "89",
                        "@ondc/org/provider_name": "La Pinoz and Pizza",
                        "rating": 5,
                        "tracking": true
                    }
                ]
when type is "Pickup", what does TAT & provider name indicate?
Haven't checked the other logs.

**Comment by BLR-0118** [comment]
@shubhamuengage

**Comment by shubhamuengage** [comment]
@BLR-0118  
1) our endpoint is https://ondc.uengage.in/ondc/on_search if buyer app concatenates the action with this endpoint 
it automatically resolves the URL all requests are sent to https://ondc.uengage.in/ondc/on_search even if it construct the url 
"https://ondc.uengage.in/ondc/on_search/on_search" it will resolve to "https://ondc.uengage.in/ondc/on_search" 

2) will fix 2nd and 3rd point

**Comment by BLR-0118** [comment]
1. /on_search - ttl of "PT1D" for provider is incorrect; should be "P1D";
2. /on_select - item attrs (returnable/cancellable/etc.) not to be shown here; also Fulfillments struct (for TAT, serviceability) is missing;
3. /on_init - there's no attr called "areaCode";
4. /on_confirm - how can the fulfillment start & end time slots be the same?
5. No /on_update API?
6. How do you plan to fulfil orders - self delivery or on-network logistics? If latter, you need to submit logs for the same.

**Comment by BLR-0118** [comment]
@shubhamuengage

**Comment by shubhamuengage** [comment]
@BLR-0118 
Point 4 : can you please tell me how time range should vary in start object and end object 
Point 5:  We do not support returns so we sending NACK in message object with error code in error object
Point 6 : we have self delivery system 
Point 7 : We support search by category and city will upload logs soon once I get the clarity on point 4

**Comment by BLR-0118** [comment]
4. fulfillment start slot is when order is picked up from store; end slot is when order is delivered to buyer; you can decide what these slots will look like;
5. You should still have /on_update returning NACK in message, right?

**Comment by shubhamuengage** [comment]
@BLR-0118 
Point 5: Yes we have NACK in message
Point 4 : So in case when an order is not picked from the outlet what should  be the values because when we receive  confirm request an order is just created. what should be the scenario in that case.

**Comment by BLR-0118** [comment]
4. You need to pass the values in /on_confirm but can use /on_update when the agent / vehicle details & start/end slots are available

**Comment by BLR-0118** [comment]
1. /on_search - need to add a struct for the fulfillment id static values. Check the updated contract [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit#)
2. return window and withholding amount are string in /on_init, /on_confirm, /on_status;
3. /on_update - there's no status for cancel. Pls check the updated contract (link above).

**Comment by BLR-0118** [comment]
@shubhamuengage

**Comment by BLR-0118** [comment]
Logs with Kotak:
1. ttl should be 30s (PT30S);
2. /on_search - can't correlate value for fulfillment_id - what does fulfillment_id of "89-1" mean? You can define these static values (check the [updated API contract](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit#) for details). This is defined in /on_select but it comes later;
3. /on_search - should be able to correlate value for location id - there's a location defined with id "89". However, items are linked to location_id "123123" which is undefined;
4. /on_search - for veg / non-veg, we're proposing values of "yes", "no" in the contract as it'll be easier for the buyer app to render their own standardized image;
5. /on_search - we're proposing "ttl" which shows a duration instead of "exp" which gives a timestamp;
6. /on_init - split the billing address & fulfillment end location address into the defined attrs like name, building, etc.;
7. Some of your timestamps & amounts (e.g. in /on_status, /on_confirm) are messed up, probably because you're getting invalid data from Kotak;
8. No /on_track, /on_support?
9. How did you generate /on_status without corresponding /status call?

**Comment by BLR-0118** [comment]
@shubhamuengage

**Comment by shubhamuengage** [comment]
@BLR-0118 
Point 8 : as Kotak did not have the functionality of track and support so we couldn't test that but you can check the logs with reference buyer app there we have uploaded the logs for track  ,and in case of support if any request comes of support we are returning nack with error code as we do not support returns.

Point 9 : There was no functionality to check the status of order so we made a unsolicited api call to Kotak to check if status was getting updated in the UI and it was getting updated 

Rest we are working on the issues motioned will update soon

**Comment by shubhamuengage** [comment]
@BLR-0118  ok let me check and will update soon

**Comment by shubhamuengage** [comment]
@BLR-0118  just tested end to end flow with kotak and these things were missing 
1) Get status of order no functionality given in ui 
2) No functionality given in ui to track the order 
3) Support functionality is also not there in the ui

Rest we are uploading the  logs with plotch with latest changes.

**Comment by BLR-0118** [comment]
1. /on_search - maximum count & available count shown for an item is per buyer only (if there's any such restriction). Here, available count seems to be total inventory and maximum count seems to be max per buyer;
2. /on_search - are you using the buyer app finder fee to calculate the declared price for an item that's displayed in the catalog?
3. Was this a COD payment? Payment type (post-fulfillment) & collected by (bpp) indicate so. However, items aren't available on COD.

**Comment by BLR-0118** [comment]
@shubhamuengage

**Comment by BLR-0118** [comment]
4. Is this your bpp_uri - https://ondc.uengage.in/ondc/on_search? This looks like the on_search endpoint (derived by appending the API name with the URI) and having this URI in the request for /select, /on_select, etc. look weird;

**Comment by BLR-0118** [comment]
5. Are you using UTC time to generate timestamp?

**Comment by shubhamuengage** [comment]
@BLR-0118 

1. We are sending the max quantity of an item that can be ordered in one go
2. No we are not including the buyer app finder fee to calculate the declared price 
3. In plotch cod was available despite  of marking items as non-cod type  so we went ahead to test with cod, also if in future we ever decide make  our items cod : true  we would  have the  cod flow tested as well but with mystore we tested with payment type : Paid by the buyer app those logs are also updated.

4. We will change the bpp_uri.

5. yes we are using utc time stamp.

**Comment by shubhamuengage** [comment]
@BLR-0118

**Comment by BLR-0118** [comment]
1. /on_search - in one case, value > maximum_value. This isn't correct;
2. /on_search - available qty & max qty are both per buyer, hence, available qty <= max qty. This isn't the case here;
3. /on_select - items should have mapping of item_id to fulfillment_id. items.quantity is removed from the contract;
4. No /on_update?

**Comment by BLR-0118** [comment]
@shubhamuengage

**Comment by shubhamuengage** [comment]
Point 1 : Fixed
Point 2 : Fixed
Point 3 : Fixed 
Point 4 : As out items are not returnable we are not getting any requests of update api and even if we get one we are sending NACK with error code 
Point 5: Yes we support search by category and city 

will update the logs soon with the changes

**Comment by shubhamuengage** [comment]
@BLR-0118

**Comment by BLR-0118** [comment]
/on_status - there is no fulfillment state "Created". Pls update with one of the states from [here](https://github.com/ONDC-Official/ONDC-Protocol-Specs/issues/26). After this fix, pls submit only this log.
@shubhamuengage

**Comment by shubhamuengage** [comment]
@BLR-0118  fixed on_status fulfillment state and raised a PR kindly review 

https://github.com/ONDC-Official/Pre-production/pull/130

**Comment by BLR-0118** [comment]
ok, just make sure you update correct fulfillment status on every change.

**Comment by shubhamuengage** [comment]
@BLR-0118  yes that is being done.
